In [9]:
import pathlib
import collections

## part 1 ##

In [1]:
testdata = '''1163751742
1381373672
2136511328
3694931569
7463417111
1319128137
1359912421
3125421639
1293138521
2311944581'''.splitlines()

In [5]:
puzzledata = pathlib.Path('day15.txt').read_text().splitlines()

In [6]:
len(puzzledata), len(puzzledata[0])

(100, 100)

In [7]:
def get_vertices(lines):
    v = {}
    for row, line in enumerate(lines):
        for col, c in enumerate(line):
            v[(row, col)] = int(c)
    return v

In [10]:
def get_adjacencies(vertices):
    adj = collections.defaultdict(list)
    for (row, col) in vertices:
        for nbr in [(row+1, col), (row-1, col), (row, col-1), (row, col+1)]:
            if nbr in vertices:
                adj[(row,col)].append(nbr)
    return adj

In [58]:
def get_graph(vertices):
    g = collections.defaultdict(dict)
    for (row, col) in vertices:
        for nbr in [(row+1, col), (row-1, col), (row, col-1), (row, col+1)]:
            if nbr in vertices:
                g[(row,col)][nbr] = vertices[nbr]
    return g

In [61]:
# from https://bradfieldcs.com/algos/graphs/dijkstras-algorithm/
import heapq


def calculate_distances(graph, starting_vertex):
    distances = {vertex: float('infinity') for vertex in graph}
    distances[starting_vertex] = 0

    pq = [(0, starting_vertex)]
    while len(pq) > 0:
        current_distance, current_vertex = heapq.heappop(pq)

        # Nodes can get added to the priority queue multiple times. We only
        # process a vertex the first time we remove it from the priority queue.
        if current_distance > distances[current_vertex]:
            continue

        for neighbor, weight in graph[current_vertex].items():
            distance = current_distance + weight

            # Only consider this new path if it's better than any path we've
            # already found.
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                heapq.heappush(pq, (distance, neighbor))

    return distances

In [62]:
testv = get_vertices(testdata)
testg = get_graph(testv)
test_distances = calculate_distances(testg, (0,0))

In [63]:
test_distances[(9,9)]

40

In [65]:
puzzlev = get_vertices(puzzledata)
puzzleg = get_graph(puzzlev)

In [68]:
puzzle_distances = calculate_distances(puzzleg, (0,0))
puzzle_distances[(99,99)]

720

## part 2 ##

In [83]:
import numpy as np

In [87]:
def get_tile(data):
    nrows, ncols = len(data), len(data[0])
    tile = np.zeros((nrows, ncols), int)
    for i,row in enumerate(data):
        for j, c in enumerate(row):
            tile[i,j] = int(c)
    return tile

In [104]:
def get_offset_tile(tile, offset):
    newtile = tile.copy()
    newtile += offset
    rows, cols = newtile.shape
    for row in range(rows):
        for col in range(cols):
            if newtile[row, col] > 9:
                newtile[row, col] -= 9
    return newtile

In [120]:
def get_fullgrid(tile):
    num_tiles = 5
    tilerows, tilecols = tile.shape
    gridrows, gridcols = num_tiles*tilerows, num_tiles*tilecols
    grid = np.zeros((gridrows, gridcols), int)
    for rtile in range(num_tiles):
        for ctile in range(num_tiles):
            offset = rtile + ctile # taxicab distance from (0,0)
            offset_tile = get_offset_tile(tile, offset)
            grid[tilerows*rtile:tilerows*(rtile+1), 
                 tilecols*ctile:tilecols*(ctile+1)] = offset_tile
    return grid           

In [121]:
def get_grid_vertices(grid):
    rows, cols = grid.shape
    v = {}
    for i in range(rows):
        for j in range(cols):
            v[(i,j)] = grid[i,j]
    return v

In [135]:
def solve(data):
    tile = get_tile(data)
    grid = get_fullgrid(tile)
    rows, cols = grid.shape
    distances = calculate_distances(get_graph(get_grid_vertices(grid)), (0,0))
    return distances[(rows-1, cols-1)]

In [136]:
solve(testdata)

315

In [122]:
testtile = get_tile(testdata)

In [123]:
testgrid = get_fullgrid(testtile)

In [126]:
testv = get_grid_vertices(testgrid)
testg = get_graph(testv)

In [127]:
testdistances = calculate_distances(testg, (0,0))

In [128]:
testdistances[(49,49)]

315

In [125]:
testv

{(0, 0): 1,
 (0, 1): 1,
 (0, 2): 6,
 (0, 3): 3,
 (0, 4): 7,
 (0, 5): 5,
 (0, 6): 1,
 (0, 7): 7,
 (0, 8): 4,
 (0, 9): 2,
 (0, 10): 2,
 (0, 11): 2,
 (0, 12): 7,
 (0, 13): 4,
 (0, 14): 8,
 (0, 15): 6,
 (0, 16): 2,
 (0, 17): 8,
 (0, 18): 5,
 (0, 19): 3,
 (0, 20): 3,
 (0, 21): 3,
 (0, 22): 8,
 (0, 23): 5,
 (0, 24): 9,
 (0, 25): 7,
 (0, 26): 3,
 (0, 27): 9,
 (0, 28): 6,
 (0, 29): 4,
 (0, 30): 4,
 (0, 31): 4,
 (0, 32): 9,
 (0, 33): 6,
 (0, 34): 1,
 (0, 35): 8,
 (0, 36): 4,
 (0, 37): 1,
 (0, 38): 7,
 (0, 39): 5,
 (0, 40): 5,
 (0, 41): 5,
 (0, 42): 1,
 (0, 43): 7,
 (0, 44): 2,
 (0, 45): 9,
 (0, 46): 5,
 (0, 47): 2,
 (0, 48): 8,
 (0, 49): 6,
 (1, 0): 1,
 (1, 1): 3,
 (1, 2): 8,
 (1, 3): 1,
 (1, 4): 3,
 (1, 5): 7,
 (1, 6): 3,
 (1, 7): 6,
 (1, 8): 7,
 (1, 9): 2,
 (1, 10): 2,
 (1, 11): 4,
 (1, 12): 9,
 (1, 13): 2,
 (1, 14): 4,
 (1, 15): 8,
 (1, 16): 4,
 (1, 17): 7,
 (1, 18): 8,
 (1, 19): 3,
 (1, 20): 3,
 (1, 21): 5,
 (1, 22): 1,
 (1, 23): 3,
 (1, 24): 5,
 (1, 25): 9,
 (1, 26): 5,
 (1, 27): 8,
 (1, 2

In [94]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [89]:
testtile

array([[1, 1, 6, 3, 7, 5, 1, 7, 4, 2],
       [1, 3, 8, 1, 3, 7, 3, 6, 7, 2],
       [2, 1, 3, 6, 5, 1, 1, 3, 2, 8],
       [3, 6, 9, 4, 9, 3, 1, 5, 6, 9],
       [7, 4, 6, 3, 4, 1, 7, 1, 1, 1],
       [1, 3, 1, 9, 1, 2, 8, 1, 3, 7],
       [1, 3, 5, 9, 9, 1, 2, 4, 2, 1],
       [3, 1, 2, 5, 4, 2, 1, 6, 3, 9],
       [1, 2, 9, 3, 1, 3, 8, 5, 2, 1],
       [2, 3, 1, 1, 9, 4, 4, 5, 8, 1]])

In [90]:
testtile + 1

array([[ 2,  2,  7,  4,  8,  6,  2,  8,  5,  3],
       [ 2,  4,  9,  2,  4,  8,  4,  7,  8,  3],
       [ 3,  2,  4,  7,  6,  2,  2,  4,  3,  9],
       [ 4,  7, 10,  5, 10,  4,  2,  6,  7, 10],
       [ 8,  5,  7,  4,  5,  2,  8,  2,  2,  2],
       [ 2,  4,  2, 10,  2,  3,  9,  2,  4,  8],
       [ 2,  4,  6, 10, 10,  2,  3,  5,  3,  2],
       [ 4,  2,  3,  6,  5,  3,  2,  7,  4, 10],
       [ 2,  3, 10,  4,  2,  4,  9,  6,  3,  2],
       [ 3,  4,  2,  2, 10,  5,  5,  6,  9,  2]])